[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc", "libopus", "ffmpeg", "libwebp", "vips"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = []

[start]
cmd = "npm run start"
