name: New Embed
description: Suggest the creation of a new bot embed template
title: "[➕][🗨️] "
labels: ["feature", "triage", "embed"]
body:
  - type: markdown
    attributes:
      value: |
        All suggestion are welcomed!
  - type: textarea
    id: description
    attributes:
      label: What your embed should show?
      description: Tell us how the embed should be used and what they show.
      placeholder: The embed should show...
    validations:
      required: true
  - type: textarea
    id: embeds
    attributes:
      label: Do you have an example embed? (optional)
      description: If you have any concept embed JSON, please attach here for make the work easier. You can use gui tools like https://glitchii.github.io/embedbuilder/ to create the embed.
      render: json
  - type: textarea
    attributes:
      label: Image Upload (Optional)
      description: Example embed image
      required: false