name: New command
description: Suggest the creation of a new bot command
title: "[➕][/] "
labels: ["feature", "triage", "command"]
body:
  - type: markdown
    attributes:
      value: |
        All suggestion are welcomed!
  - type: textarea
    id: description
    attributes:
      label: What your command should do?
      description: Tell us how the command should work and what they do.
      placeholder: The command should say hello to the user...
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category the command should enter
      options:
        - Other
        - Moderation
        - Fun
        - Info
        - Music
        - NSFW
        - Tools
        - Config
  - type: checkboxes
    id: nsfw
    attributes:
      label: Is the command NSFW?
      description: Should the command can only be runned only on nsfw channels?
      options:
        - label: The command is NSFW
          required: false
  - type: dropdown
    id: nsfw
    attributes:
      label: Is the command NSFW?
      description: Should the command can only be runned only on nsfw channels?
      options:
        - No, the command is not NSFW and can be used on any channel (default)
        - Yes, the command is NSFW and can be used only on nsfw channels
      default: 0
      validations:
        required: true
  - type: textarea
    id: embeds
    attributes:
      label: Embed design (optional)
      description: If you have any concept embed JSON, please attach here for make the work easier
      render: json
