name: Deploy

on:
    push:
        branches: [main]
    # pull_request:
    #   branches: [ main ]

jobs:
    bump:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            # Increase version
            - name: "Automated Github Action Version Bump"
              uses: "rimonhanna/gh-action-bump-version@master"
              with:
                  tag-prefix: ""
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            # setup Docker buld action
            - name: Publish to fernandomema/zumito on Docker Hub
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: fernandomema/zumito
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  dockerfile: ./Dockerfile
                  context: ./
                  tags: ${{ steps.bump_version.outputs.next-version }}
            - name: "✏️ Generate release changelog"
              uses: heinrichreimer/github-changelog-generator-action@v2.3
              id: changelog
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CHANGELOG }}
              uses: Ilshidur/action-discord@master
              with:
                args: "Zumito has been updated: ${{ steps.changelog.outputs.changelog }}"
