name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint-javascript:
    name: Lint JavaScript Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: "./eslint.config.mjs"
          extra_args: "--max-warnings=0"